name: Java CI with Maven

on:
  push:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Checkout code
    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
    
    # Build with Maven
    - name: Build with Maven
      run: mvn test

    # Optional: List contents of the target directory for debugging
    - name: List work directory
      run: ls -R /home/runner/work/

    # Publish Surefire Test Report
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: 'target/surefire-reports/TEST-*.xml'  # Correct relative path for Surefire reports
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Automation Tests Report

    # Publish Extent Reports (Ensure reports directory is in the correct path)
    - name: Publish Extent Reports
      if: success() || failure()
      uses: peaceiris/actions-gh-pages@v3
      with:
          publish_dir: 'reports'  # Correct relative path for Extent report directory
          github_token: ${{ secrets.GITHUB_TOKEN }}
